name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v0.1, v0.2)"
        required: true
        type: string
      prerelease:
        description: "Mark as prerelease"
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate version format
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?(-[a-zA-Z0-9-]+)?$ ]]; then
            echo "Error: Version must be in format v1.0, v1.0.0, or v1.0-beta"
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if tag already exists
        run: |
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Error: Tag $VERSION already exists"
            exit 1
          fi

      - name: Read release notes
        id: release-notes
        run: |
          if [[ -f "web/RELEASE_NOTES.md" ]]; then
            VERSION_HEADER="# Release Notes"
            NEXT_VERSION_PATTERN="^## v[0-9]"
            VERSION_LINE=$(grep -n "## $VERSION" web/RELEASE_NOTES.md | cut -d: -f1)
            if [[ -n "$VERSION_LINE" ]]; then
              NEXT_VERSION_LINE=$(tail -n +$((VERSION_LINE + 1)) web/RELEASE_NOTES.md | grep -n "$NEXT_VERSION_PATTERN" | head -1 | cut -d: -f1)
              if [[ -n "$NEXT_VERSION_LINE" ]]; then
                tail -n +$VERSION_LINE web/RELEASE_NOTES.md | head -n $((NEXT_VERSION_LINE - 1)) > release_notes.md
              else
                tail -n +$VERSION_LINE web/RELEASE_NOTES.md > release_notes.md
              fi
              sed -i '1d' release_notes.md
              sed -i -e :a -e '/^\s*$/d;N;ba' release_notes.md
              echo "Release notes extracted successfully"
            else
              echo "Warning: Version $VERSION not found in RELEASE_NOTES.md, using full file"
              cp web/RELEASE_NOTES.md release_notes.md
            fi
          else
            echo "Warning: web/RELEASE_NOTES.md not found, creating default release notes"
            cat > release_notes.md << EOF
          # Release $VERSION

          This is a manual release of version $VERSION.

          ## Changes
          - Manual release created via GitHub Actions
          - Version: $VERSION
          - Release Date: $(date -u +"%Y-%m-%d")
          EOF
          fi

          {
            echo "RELEASE_NOTES<<EOF"
            cat release_notes.md
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Update VERSION file
        run: |
          echo "$VERSION" > web/VERSION
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add web/VERSION
          git commit -m "Bump version to $VERSION" || echo "No changes to commit"

      - name: Create and push tag
        run: |
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"
          git push origin main

      # --- NEW: ensure lowercase image path for GHCR
      - name: Derive lowercase repo for GHCR
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # --- NEW: login to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- NEW: force a docker-container Buildx builder
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}:${{ env.VERSION }}
            ghcr.io/${{ env.REPO_LC }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO_LC }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO_LC }}:buildcache,mode=max

      - name: Summary
        run: |
          echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Prerelease**: ${{ github.event.inputs.prerelease }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker Image**: ghcr.io/${{ env.REPO_LC }}:${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Release Notes**: Extracted from web/RELEASE_NOTES.md" >> $GITHUB_STEP_SUMMARY
