name: release-build-push

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read VERSION
        id: version
        run: echo "version=$(cat web/VERSION)" >> $GITHUB_OUTPUT

      - name: Ensure tag matches VERSION
        run: |
          TAG="${GITHUB_REF##*/}"
          VERSION_FILE="${{ steps.version.outputs.version }}"
          if [ "$TAG" != "$VERSION_FILE" ]; then
            echo "Release tag ($TAG) does not match VERSION file ($VERSION_FILE)." >&2
            exit 1
          fi

      - name: Ensure VERSION bumped vs main
        run: |
          git fetch --depth=1 origin main
          if git rev-parse --verify origin/main >/dev/null 2>&1; then
            if git show origin/main:web/VERSION >/dev/null 2>&1; then
              PREV=$(git show origin/main:web/VERSION || true)
              CURR=$(cat web/VERSION)
              if [ "$PREV" = "$CURR" ]; then
                echo "VERSION not bumped (still $CURR vs main)." >&2
                exit 1
              fi
            fi
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
